name = input("Enter the name: ")
age = int(input("Enter the age: "))
address = input("Enter the address: ")
course = input("Enter the course: ")
lang = input("Enter the language: ")
birth = input("Enter the birth date: ")
height = float(input("Enter the height: "))
star = input("Enter the star sign: ")
favsub = input("Enter the favourite subject: ")
sport = input("Enter the sport: ")

print("-----Partner's Information-----")
print("Name:", name)
print("Age:", age)
print("Address:", address)
print("Course:", course)
print("Language:", lang)
print("Birth Date:", birth)
print("Height:", height)
print("Star sign:", star)
print("Favourite Subject:", favsub)
print("Sport:", sport)

